[package]
name = "Nakama-AMM"
version = "0.0.2"
edition = "legacy"
published-at = "0x28974728bd73ce1c6bf66c6ecb750b988c61fa5b01e491754562cf1bcf8714e9"


[dependencies]
# Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }
Iota = { git = "https://github.com/iotaledger/iota.git", subdir = "crates/iota-framework/packages/iota-framework", rev = "testnet" }


[addresses]
nakama_amm = "0x0"
iota = "0x2"


# staking admin
treasury_admin = "0x989355841c92853ce05e057bdde08bdcb880ea85fc0dfe5428691d2b355735a7"
stake_emergency_admin = "0x989355841c92853ce05e057bdde08bdcb880ea85fc0dfe5428691d2b355735a7"

# staking test addresses.
treasury = "0x13"
emergency = "0x14"
alice = "0x15"
bob = "0x16"